# Generated by Django 3.2 on 2023-08-03 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobNumber', models.CharField(max_length=30, verbose_name='工单号')),
                ('associateNumber', models.CharField(max_length=50, verbose_name='收集表工单号')),
                ('handler', models.CharField(max_length=30, verbose_name='处理人')),
                ('complaintType', models.CharField(max_length=30, verbose_name='投诉类型')),
                ('jobType', models.CharField(max_length=30, verbose_name='工单类型')),
                ('date', models.DateTimeField(auto_now_add=True, max_length=30, verbose_name='工单号')),
                ('address', models.CharField(max_length=50, verbose_name='投诉地址')),
                ('detailAddress', models.CharField(max_length=50, verbose_name='经纬度')),
                ('images', models.ImageField(upload_to='', verbose_name='相关图片')),
                ('testResult', models.ImageField(upload_to='', verbose_name='掌上优测试截图')),
                ('sign', models.BooleanField(verbose_name='是否有联通信号')),
                ('position', models.ImageField(blank=True, upload_to='', verbose_name='问题定位图')),
                ('reason', models.CharField(max_length=50, verbose_name='投诉原因')),
                ('soluType', models.CharField(max_length=50, verbose_name='方案类型')),
                ('testReport', models.FileField(blank=True, upload_to='')),
                ('isSolve', models.BooleanField(verbose_name='是否解决')),
                ('desc', models.ImageField(blank=True, upload_to='', verbose_name='解决截图说明')),
                ('remarks', models.CharField(max_length=100, verbose_name='备注')),
            ],
            options={
                'verbose_name': '客服现场处理信息收集表',
            },
        ),
    ]
