# Generated by Django 3.2 on 2023-08-03 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectioninfo',
            name='date',
            field=models.DateTimeField(max_length=30, verbose_name='处理时间'),
        ),
    ]
