# Generated by Django 3.2 on 2023-08-04 09:21

import collection.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_alter_collectioninfo_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectioninfo',
            name='id',
        ),
        migrations.AddField(
            model_name='collectioninfo',
            name='submit_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='提交时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='collectioninfo',
            name='submitter',
            field=models.CharField(default='暂无', max_length=20, verbose_name='提交者'),
        ),
        migrations.AlterField(
            model_name='collectioninfo',
            name='desc',
            field=models.ImageField(blank=True, upload_to=collection.models.directory_path, verbose_name='解决截图说明'),
        ),
        migrations.AlterField(
            model_name='collectioninfo',
            name='detailAddress',
            field=models.CharField(blank=True, max_length=50, verbose_name='经纬度'),
        ),
        migrations.AlterField(
            model_name='collectioninfo',
            name='images',
            field=models.ImageField(blank=True, upload_to=collection.models.directory_path, verbose_name='相关图片'),
        ),
        migrations.AlterField(
            model_name='collectioninfo',
            name='jobNumber',
            field=models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='工单号'),
        ),
        migrations.AlterField(
            model_name='collectioninfo',
            name='position',
            field=models.ImageField(blank=True, upload_to=collection.models.directory_path, verbose_name='问题定位图'),
        ),
        migrations.AlterField(
            model_name='collectioninfo',
            name='testReport',
            field=models.FileField(blank=True, upload_to=collection.models.directory_path, verbose_name='测试报告/测试需求'),
        ),
        migrations.AlterField(
            model_name='collectioninfo',
            name='testResult',
            field=models.ImageField(blank=True, upload_to=collection.models.directory_path, verbose_name='掌上优测试截图'),
        ),
    ]
