# Generated by Django 3.2 on 2023-08-07 01:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0003_auto_20230804_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectioninfo',
            name='submit_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='提交时间'),
        ),
    ]
