# Generated by Django 3.2 on 2023-08-07 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0004_alter_collectioninfo_submit_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectioninfo',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='collectioninfo',
            name='jobNumber',
            field=models.CharField(max_length=30, unique=True, verbose_name='工单号'),
        ),
    ]
