# Generated by Django 3.2 on 2023-08-09 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0005_auto_20230807_1126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectioninfo',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='collectioninfo',
            name='images',
        ),
        migrations.RemoveField(
            model_name='collectioninfo',
            name='position',
        ),
        migrations.RemoveField(
            model_name='collectioninfo',
            name='testReport',
        ),
        migrations.RemoveField(
            model_name='collectioninfo',
            name='testResult',
        ),
        migrations.AddField(
            model_name='collectioninfo',
            name='desc_path',
            field=models.CharField(blank=True, max_length=200, verbose_name='解决截图说明'),
        ),
        migrations.AddField(
            model_name='collectioninfo',
            name='images_path',
            field=models.CharField(blank=True, max_length=200, verbose_name='相关图片'),
        ),
        migrations.AddField(
            model_name='collectioninfo',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=9, verbose_name='纬度'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='collectioninfo',
            name='location',
            field=models.CharField(blank=True, max_length=200, verbose_name='问题定位图'),
        ),
        migrations.AddField(
            model_name='collectioninfo',
            name='lon',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=9, verbose_name='经度'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='collectioninfo',
            name='testReport_path',
            field=models.CharField(blank=True, max_length=200, verbose_name='测试报告/测试需求'),
        ),
        migrations.AddField(
            model_name='collectioninfo',
            name='testResult_path',
            field=models.CharField(blank=True, max_length=200, verbose_name='掌上优测试截图'),
        ),
    ]
