# Generated by Django 3.2 on 2023-08-09 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0006_auto_20230809_1235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectioninfo',
            name='detailAddress',
        ),
    ]
