# Generated by Django 3.2 on 2023-08-09 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0007_remove_collectioninfo_detailaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectioninfo',
            name='desc_path',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='解决截图说明'),
        ),
        migrations.AlterField(
            model_name='collectioninfo',
            name='images_path',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='相关图片'),
        ),
        migrations.AlterField(
            model_name='collectioninfo',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='问题定位图'),
        ),
        migrations.AlterField(
            model_name='collectioninfo',
            name='testReport_path',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='测试报告/测试需求'),
        ),
        migrations.AlterField(
            model_name='collectioninfo',
            name='testResult_path',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='掌上优测试截图'),
        ),
    ]
