# Generated by Django 3.2 on 2023-08-09 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0008_auto_20230809_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectioninfo',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='纬度'),
        ),
        migrations.AlterField(
            model_name='collectioninfo',
            name='lon',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='经度'),
        ),
        migrations.AlterField(
            model_name='collectioninfo',
            name='remarks',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='备注'),
        ),
    ]
