# Generated by Django 3.2 on 2023-08-09 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0009_auto_20230809_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectioninfo',
            name='complaintType',
            field=models.CharField(max_length=50, verbose_name='投诉类型'),
        ),
        migrations.AlterField(
            model_name='collectioninfo',
            name='date',
            field=models.DateTimeField(max_length=50, verbose_name='处理时间'),
        ),
        migrations.AlterField(
            model_name='collectioninfo',
            name='desc_path',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='解决截图说明'),
        ),
        migrations.AlterField(
            model_name='collectioninfo',
            name='images_path',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='相关图片'),
        ),
        migrations.AlterField(
            model_name='collectioninfo',
            name='jobType',
            field=models.CharField(max_length=50, verbose_name='工单类型'),
        ),
        migrations.AlterField(
            model_name='collectioninfo',
            name='location',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='问题定位图'),
        ),
        migrations.AlterField(
            model_name='collectioninfo',
            name='remarks',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='collectioninfo',
            name='submitter',
            field=models.CharField(default='暂无', max_length=1000, verbose_name='提交者'),
        ),
        migrations.AlterField(
            model_name='collectioninfo',
            name='testReport_path',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='测试报告/测试需求'),
        ),
        migrations.AlterField(
            model_name='collectioninfo',
            name='testResult_path',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='掌上优测试截图'),
        ),
    ]
