# Generated by Django 3.2 on 2023-08-17 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0015_alter_collectioninfo_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectioninfo',
            name='soluType',
            field=models.CharField(max_length=150, verbose_name='方案类型'),
        ),
    ]
