# Generated by Django 3.2 on 2023-08-17 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0016_alter_collectioninfo_solutype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectioninfo',
            name='complaintType',
            field=models.CharField(choices=[('4G', '4G'), ('5G', '5G'), ('VOLTE', 'VOLTE'), ('VONR', 'VONR'), ('NB', 'NB')], max_length=50, verbose_name='投诉类型'),
        ),
    ]
