# Generated by Django 3.2 on 2023-08-17 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timemodel',
            name='month',
        ),
        migrations.AddField(
            model_name='timemodel',
            name='report_link',
            field=models.CharField(default='', max_length=20, verbose_name='数据分析结果'),
        ),
        migrations.AddField(
            model_name='timemodel',
            name='timestamp',
            field=models.CharField(default='', max_length=20, verbose_name='时间'),
        ),
    ]
