# Generated by Django 3.2 on 2023-08-17 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_alter_timemodel_timestamp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TimeModel',
        ),
    ]
