# Generated by Django 3.2 on 2023-08-17 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0005_timemodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timemodel',
            options={'verbose_name': '数据分析记录'},
        ),
    ]
