# Generated by Django 3.2 on 2023-08-07 01:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='uname',
            field=models.CharField(default=django.utils.timezone.now, max_length=20, verbose_name='用户名'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='username',
            field=models.CharField(max_length=20, unique=True, verbose_name='账号'),
        ),
    ]
